/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_acinq_bitcoin_ConsensusWrapper */

#ifndef _Included_fr_acinq_bitcoin_ConsensusWrapper
#define _Included_fr_acinq_bitcoin_ConsensusWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_acinq_bitcoin_ConsensusWrapper
 * Method:    VerifyScript
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_fr_acinq_bitcoin_ConsensusWrapper_VerifyScript
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
